from linked_list.implementation.linked_list import LinkedList
from doubly_linked_list.implementation.doubly_linked_list import DoublyLinkedList
from circular_linked_list.implementation.circular_linked_list import CircularLinkedList