name: Release to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger only when you push a tag like v0.2.0

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish
        uses: PyO3/maturin-action@v1
        env:
          # Using your official PyPI token secret
          MATURIN_PYPI_TOKEN: ${{ secrets.BURMESE_NATIVE }}
        with:
          command: publish
          # Added --manylinux 2014 to ensure compatibility
          args: --manylinux 2014 --interpreter python3 --manifest-path rust_queue/Cargo.toml
