name: Publish to TestPyPI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish
        # This action automatically uses a Docker container for manylinux
        uses: PyO3/maturin-action@v1
        env:
          # Use your TestPyPI token here
          MATURIN_PYPI_TOKEN: ${{ secrets.KUUKING_DSA_TOKEN }}
          # Tell it to use TestPyPI instead of real PyPI
          MATURIN_REPOSITORY_URL: https://test.pypi.org/legacy/
        with:
          command: publish
          # This 'manylinux' setting triggers the Docker container build
          args: --manylinux 2014 --interpreter python3 --manifest-path rust_queue/Cargo.toml
